version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - '4000:4000'
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/data:/app/data
    environment:
      - PORT=4000
      - NODE_ENV=production

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5173:5173'
    command: sh -c "npm ci && npm run dev -- --host"
