name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps
        run: npm ci

      - name: Install server deps
        run: npm ci
        working-directory: server

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build (sanity)
        run: npm run build

      - name: Start backend (4100)
        run: |
          nohup bash -lc 'PORT=4100 node server/index.js' >/tmp/backend.log 2>&1 &

      - name: Start frontend (Vite 5173)
        run: |
          nohup bash -lc 'npm run dev' >/tmp/frontend.log 2>&1 &

      - name: Wait for services
        run: npx wait-on http://localhost:4100/health http://localhost:5173 --timeout 300000

      - name: Run Playwright tests
        env:
          APP_URL: http://localhost:5173
          BACKEND_URL: http://localhost:4100
        run: npx playwright test tests/ui.spec.js tests/appointment.spec.js --browser=chromium --timeout=45000

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
